import LeftBar from "@/components/leftBar/LeftBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RightBar from "@/components/rightBar/RightBar";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  
  /*pseudo auth */
  let sessionTrue = false;

  const SessionLayout = ({ children }: { children: React.ReactNode }): React.ReactNode => {
    return (
      <div className="min-h-screen flex mx-auto md:w-[95%] xl:w-[95%] 2xl:w-[70%]">
        <LeftBar />
        <div className="bg-blue-500 w-[88%] lg:w-[58%] xl:w-[48%]">
          {children}
        </div>
        <RightBar />
      </div>
    );
  };

  const NoSessionLayout = ({
    children,
  }: {
    children: React.ReactNode;
  }): React.ReactNode => {
    return <>{children}</>;
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        {sessionTrue ? (
          <SessionLayout>{children}</SessionLayout>
        ) : (
          <NoSessionLayout>{children}</NoSessionLayout>
        )}
      </body>
    </html>
  );
}
