import LeftBar from "@/components/leftBar/LeftBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RightBar from "@/components/rightBar/RightBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex mx-auto w-[80%] md:w-[95%] xl:w-[95%] 2xl:w-[70%]">
          <LeftBar />
          <div className="bg-rose-500 w-[88%] lg:w-[58%] xl:w-[45%]">
          {children}
          </div>
          <RightBar />
        </div>
      </body>
    </html>
  );
}
